### ISSUE TITLE
InfinityLoader.exe

### ISSUE THREAD

**Issue by dive-bomber** [Bubb13/EEex#42]
Both Opera and Edge are very pissy about this file, won't let me download it even with the whole zip. They claim it's a virus ("omg, an exe file!!"), downloading it via 'save as' and changing extension back and forth didn't seem to work, windows says that "this app can't run on your PC".

**Comment by dive-bomber** [comment]
Downloaded "tar.gz" version and for some whatever reason, it didn't have a problem with that. It works fine.

**Comment by suy** [comment]
Because the tar.gz is the source code, not the binaries. This is what the release contains:

![image](https://user-images.githubusercontent.com/1200609/142498774-aa41d044-ca53-4018-81eb-7366e8c3388e.png)
