### ISSUE TITLE
Several Effects Granting Extra Attacks Not Functioning

### ISSUE THREAD

**Issue by JoeGalt** [Bubb13/EEex#44]
I have encountered several cases of effects not granting the extra attacks they are supposed to. This occurs when using just EEex 0.9.6 on the latest Steam version of both BG1 EE and BG2 EE, without any other mods installed and when launching the game using InfinityLauncher.exe. Attached is my weidu log.

Weapons like Belm that grant additional attacks per round, are not granting any extra attacks.

The Blade's Offensive Spin grants extra attacks only up to two per round. If the character using offensive spin has two or more attacks without it, such as by using a bow or dual wielding, offensive spin will not grant an extra attack but its other effects will function.

[WeiDU.log](https://github.com/Bubb13/EEex/files/8608281/WeiDU.log)

**Comment by Bubb13** [comment]
Fixed in master, thanks for reporting!
