### ISSUE TITLE
CTD in UI Edit Mode

### ISSUE THREAD

**Issue by artyfox** [Bubb13/EEex#47]
Running BGEE or BG2EE with EEex seems to crash whenever a UI element is clicked in UI Edit Mode.

Here are the steap to reproduce on a fresh install of either EE game (BGEE+SOD+DLCMerger / BG2EE).

1. Install EEex (with all options)
> ```
> ~EEEX/EEEX.TP2~ #0 #0 // EEex: 0.9.7
> ~EEEX/EEEX.TP2~ #0 #1 // Enable effect menu module - (LShift-on-hover to view spells affecting creature): 0.9.7
> ~EEEX/EEEX.TP2~ #0 #2 // Enable timer module - (visual indicators for modal actions, contingency spells, and spell/item cooldowns): 0.9.7
> ```
2. Run game via `InfinityLoader.exe` and set in-game graphics options Fullscreen 'Off', Scaled Mode 'On'
3. Add `SetPrivateProfileString('Program Options','UI Edit Mode','1')` line to `Baldur.lua`
4. Run game via `InfinityLoader.exe` and press F11
5. Click on any UI element, and the resulting crash will occur
> <img src="https://user-images.githubusercontent.com/45717702/177222723-4137ce33-155d-41a2-acac-3231fc8a2dce.png" width="200" />

Running `InfinityLoader.exe` as administrator still crashes as above. Launching via `Baldur.exe`, will allow UI edits to work normally.

Anybody have any workarounds? 🦊

**Comment by Bubb13** [comment]
This is fixed in master — thanks for reporting!
