### ISSUE TITLE
Dragonspear UI++ and EEex - lag issues while on mage/cleric spellbook and inventory screens.

### ISSUE THREAD

**Issue by pzajas** [Bubb13/EEex#48]
As written in the title. I have the 'EEex' and 'Dragonspear UI++' mods installed. While browsing my inventory screen or mage/cleric spellbook the framerate goes down dramatically. Any idea what may be the cause of this issue?

**Comment by Bubb13** [comment]
Quoting one of my forum posts:

> The original version of Dragonspear UI++ spams Lua errors in the spell book. The way InfinityLoader hooks into the game means that logging these errors takes significantly longer, effectively freezing the game.
> 
> From what I can tell, the latest version of Dragonspear UI++ is downloaded from the dropbox link in skusha's post:
> https://forums.beamdog.com/discussion/comment/1185394/#Comment_1185394
> 
> This version has the Lua errors fixed and should work with EEex.

**Comment by pzajas** [comment]
Oh nice - ill check this insta and will writee here if that works. Thanks for the very quick reply! :*

**Comment by Bubb13** [comment]
Great, glad it's resolved. Have fun!
