### ISSUE TITLE
InfinityLoader.exe not running on BG1EE and errors with 2.5 EEex mods

### ISSUE THREAD

**Issue by Endarire** [Bubb13/EEex#49]
Greetings, @Bubb13!

Today, I tested EEex 0.9.7 on BG1EE 2.6.6 for Windows.  I used DLCMerger as the first installed mod as normal and things seemed to work.  I installed all components of OlvynSpells 2.2 (the newest edition) and got the same runtime errors as those listed here., but no  installation errors.  Since this initial test, running InfinityLoader.exe briefly pops up a window, seems to run something, then immediately closes but BG doesn't load.

![image](https://user-images.githubusercontent.com/10439725/182526411-30c682ee-262f-4d0e-901f-1a2fc1208fd9.png)

Running Baldur.exe directly gives these errors but at least the program loads after these error messages close.
![image](https://user-images.githubusercontent.com/10439725/182526625-843bb4b4-ec71-45a0-ad40-483491120ce4.png)

![image](https://user-images.githubusercontent.com/10439725/182526642-579b0ca4-e141-4765-b4a9-626b75617927.png)

![image](https://user-images.githubusercontent.com/10439725/182526664-c2d117f0-2ba7-441a-8021-a257babdae37.png)

I later tried installing all components of Epic Thieving 3.5 (the latest release) and its Poison Use thieving skill refused to install.

Thankee!

**Comment by Endarire** [comment]
My WeiDU.log is listed below.

// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~DLCMERGER/DLCMERGER.TP2~ #0 #1 // Merge DLC into game -> Merge "Siege of Dragonspear" DLC: 1.3
~EEEX/EEEX.TP2~ #0 #0 // EEex: 0.9.7
~EEEX/EEEX.TP2~ #0 #1 // Enable effect menu module - (LShift-on-hover to view spells affecting creature): 0.9.7
~EEEX/EEEX.TP2~ #0 #2 // Enable timer module - (visual indicators for modal actions, contingency spells, and spell/item cooldowns): 0.9.7
~EPICTHIEVING/EPICTHIEVING.TP2~ #0 #0 // Epic Locks
~EPICTHIEVING/EPICTHIEVING.TP2~ #0 #100 // Epic Traps
~EPICTHIEVING/EPICTHIEVING.TP2~ #0 #200 // Epic Trap Setting
~EPICTHIEVING/EPICTHIEVING.TP2~ #0 #300 // Epic Pickpocketing
~EPICTHIEVING/EPICTHIEVING.TP2~ #0 #400 // Epic Detect Illusions
~EPICTHIEVING/EPICTHIEVING.TP2~ #0 #500 // Prevent multiple Potions of Perception or Master Thievery from stacking
~MESPELLS/MESPELLS.TP2~ #0 #11013 // Improve Bless and (if in-game) Curse -> A and B: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #11021 // Make it so that Command takes control of the target for 1 round instead of putting them to sleep: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #11053 // Improve Entangle -> A and B: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #11061 // Improve Magical Stone: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #12091 // Turn Know Alignment into Identify Creature, which reveals info about the target (e.g. HP, stats, resistances): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #14131 // Increase the duration of Negative Plane Protection to 8 hours: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #14161 // Improve Cloak of Fear: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #15031 // 3E-like Flame Strike and Fire Storm: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #15071 // Make it so Champion's Strength sets the target's Strength to 25 (but it still prevents the caster from casting any more spells for the duration): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #17041 // Make it so Nature's Beauty charms enemies rather than blinding or killing them: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #14021 // Original BG1-style Monster Summoning and Animal Summoning spells: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #25011 // Restore original BG1 Animate Dead (one skeleton per level, which ignore the summoning limit) -> Restore original Animate Dead for both priests and wizards: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #17261 // Weaken devas but allow more than one to be summoned at once: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #21111 // Turn Infravision into True Strike, which grants a large THAC0 bonus for a short duration: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #21161 // Revise Sleep (no Hit Dice limit, but lasts shorter and creatures will wake up when damaged): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #22201 // Revise Power Word, Sleep (no HP limit, but lasts shorter and the creature will wake up when damaged): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #21151 // Improve Shocking Grasp, Chill Touch and Ghoul Touch: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #21191 // Improve Larloch's Minor Drain and Vampiric Touch: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #21231 // Allow familiars to deliver the wizard's touch spells: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #22031 // Improve low-level spells that detect illusions: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #22211 // Improve spells that merely weaken enemies rather than disable them (e.g. Deafness, Ray of Enfeeblement, Contagion): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #23131 // Have Skull Trap cap at 10d6 damage: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #24042 // Improve Ice Storm -> IWD-style improved Ice Storm: 6d10 damage all at once: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #24081 // Prevent Stoneskin from making characters grey (should be installed after AI mods like SCS): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #24131 // Restore original BG1 Otiluke's Resilient Sphere (no saving throw): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #25031 // Restore original BG1 Cone of Cold (the cone is larger the farther away the target is; the spell's maximum range increases based on caster level): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #25151 // Make it so the spell Oracle lets you foresee what spells enemies are going to cast (like Spellcraft in 3rd-edition games): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #26071 // Make it so Mislead's invisibility becomes partial invisibility when you attack or cast a spell, just like Improved Invisibility (regardless of whether the image is still alive): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #26111 // Make it so Protection from Magical Weapons only lasts 3 rounds but Absolute Immunity lasts 5 rounds: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #26151 // Improve Chain Lightning: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #27121 // Improve Delayed Blast Fireball (1d6 per level, up to 20d6): 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #29111 // Make Meteor Swarm bombard the area randomly with small meteors rather than a single area of effect: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #29141 // Improve Energy Drain: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #29221 // Revise Comet and Dragon's Breath: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #26171 // Let Contingency and Chain Contingency be cast as a free action: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #14151 // Let Farsight be cast as a free action: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #23011 // Let Clairvoyance be cast indoors: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #980 // Let Rangers and Paladins gain spells quicker and up to 6th-level spells: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #990 // Let Rangers and Paladins cast spells at their full caster level: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #1000 // New spells -> Add all the new spells to the game, including the really powerful spells: 2.2.0
~MESPELLS/MESPELLS.TP2~ #0 #1100 // Add 3E-like Metamagic abilities to the game: 2.2.0
~ANIMALCOMPANIONS/SETUP-ANIMALCOMPANIONS.TP2~ #0 #0 // Animal Companions For All Rangers (Optional: Druids): 1.6
~FNP_MULTICLASS/FNP_MULTICLASS.TP2~ #0 #91 // Multiclass Druids: 0.83.11
~FNP_MULTICLASS/FNP_MULTICLASS.TP2~ #0 #92 // Multiclass Shamans: 0.83.11
~FNP_MULTICLASS/FNP_MULTICLASS.TP2~ #0 #95 // Multiclass Cleric kits (install AFTER all other kit mods!!): 0.83.11
~FNP_MULTICLASS/FNP_MULTICLASS.TP2~ #0 #99 // Apply FnP multiclass kits to NPCs: 0.83.11
~C0WARLOCK/C0WARLOCK.TP2~ #0 #0 // Warlock Kit: 1.72

**Comment by Bubb13** [comment]
EEex v0.9.7-alpha does not contain all of the features of v0.8.7-alpha. I'm slowly building up to have feature parity, but in the meantime mods made for EE v2.5 + EEex 0.8.7-alpha will not work.

**Comment by Endarire** [comment]
@Bubb13 
I mentioned this in the Issues section to show at least some important functionality from 2.5's EEex to reimplement and to notify you that InfinityLoader.exe worked only unreliably for me.

Thankee!

**Comment by Bubb13** [comment]
Can you confirm that InfinityLoader.exe works if you **only** install EEex?
