### ISSUE TITLE
In game scrollbars don't work after launching from infinity launcher (From 9.8 alpha. )

### ISSUE THREAD

**Issue by AldoLamarre** [Bubb13/EEex#50]
Didn't have the bug on the old version 9.7 in my older laptop. Launching the game normally and the bar moves. 

Will try to test with 9.7 tomorrow if it doesn't break my mod install order.

**Comment by Bubb13** [comment]
Thanks for reporting — fixed in [v0.9.9-alpha](https://github.com/Bubb13/EEex/releases/tag/v0.9.9-alpha).
