### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by Stevenozzz** [Bubb13/EEex#51]
Eex (all components installed) makes my game freeze (not a complete freeze, just frame refreshes every minute or so, and there is no crash) when I open inventory or any other game menu (character, spellbooks, etc), but only in BG2. Bg1 with the same mods works fine.

My game version is 2.6.6.0
and mods: 
DragonspearUI++
Spell Revisions
IWDification
SCS
CDtweaks

EDIT: I narrowed down the issue being introduced by dragonspearUI++

**Comment by Bubb13** [comment]
Which version of EEex are you using? The interaction with DragonspearUI++ was supposed to be fixed in [v0.9.9-alpha](https://github.com/Bubb13/EEex/releases/tag/v0.9.9-alpha).

**Comment by Stevenozzz** [comment]
I'm testing on latest release of both dragonspearUI and EEx (0.9.9)
I'll try redownloading bg2 tomorrow and check if my installation was just bad.

**Comment by Bubb13** [comment]
Fixed in [v0.9.10-alpha](https://github.com/Bubb13/EEex/releases/tag/v0.9.10-alpha).
