### ISSUE TITLE
Crash when running InfinityLoader.exe with EEex 0.9.11 or newer

### ISSUE THREAD

**Issue by JoeGalt** [Bubb13/EEex#54]
I am having an issue where BG1 EE crashes when using EEex 0.9.11 or newer when running InfinityLoader.exe. The game does not start up at all, it immediately returns the 'Baldurs Gate has crashed' error message. This occurred whether I installed all components or just the base EEex component. I am able to use EEex 0.9.10 without this crash occurring. I am using 64 bit windows 7.

**Comment by Bubb13** [comment]
Odd, multiple people have reported issues with versions >= v0.9.11, though report different symptoms. You say the game crashes - for others the loader seems to quietly exit. Is a crash .dmp generated? It should be in Documents/Infinity Engine - Enhanced Edition/crash, or in your game's folder, (next to the .exe).

The only major change between v0.9.10 and v0.9.11 is pattern caching and a change to the rand() pattern, and I can't think of a reason why either of those would introduce problems.

**Comment by Bubb13** [comment]
@JoeGalt I think I have fixed the issue. Please try this version: [https://github.com/Bubb13/EEex/releases/tag/v0.9.15-alpha](https://github.com/Bubb13/EEex/releases/tag/v0.9.15-alpha)

**Comment by JoeGalt** [comment]
> @JoeGalt I think I have fixed the issue. Please try this version: https://github.com/Bubb13/EEex/releases/tag/v0.9.15-alpha

0.9.15 works, thanks for getting to this so quickly.
