### ISSUE TITLE
Buttons pressed

### ISSUE THREAD

**Issue by theernestrain** [Bubb13/EEex#56]
What do i need to disable to remove the buttons pressed notifications?

**Comment by Bubb13** [comment]
If you accidentally toggled it on, you want to press the backtick (`` ` ``) key.

To change the keybind, open `override/B3Hotkey.lua`, and locate the following line under `B3Hotkey_Hotkeys`
```lua
{function() B3Hotkey_TogglePrintKeys() end, {}, {0x60}},                               -- Key-Pressed Output Toggle ('`')
```
Change `0x60` to whatever key you wish, using the "[EEex] Pressed:" output from before to get the corresponding keycode.
To disable the keybind completely, prepend ``--`` to the start of the line.

**Comment by theernestrain** [comment]
Thanks a lot for your help
