### ISSUE TITLE
The game crashed when I cast Magic Fang (SR) on my minions. 

### ISSUE THREAD

**Issue by myevilmode** [Bubb13/EEex#70]
[dump.2.6.6.0.0018.zip](https://github.com/Bubb13/EEex/files/14511010/dump.2.6.6.0.0018.zip)
[WeiDU.log](https://github.com/Bubb13/EEex/files/14511014/WeiDU.log)

**Comment by Bubb13** [comment]
One of your mods applied an `op232` with `param2 = 10` and `special = 0`. This results in a divide by zero and crashes the game. Closing as a non-EEex issue.

**Comment by myevilmode** [comment]
Can you please tell me what mod this is so that I can report it to the creator?
