### ISSUE TITLE
After installing EEex, the game save location has changed

### ISSUE THREAD

**Issue by MephistoSatanDevil** [Bubb13/EEex#74]
After installing EEex, the game save location has changed to the root directory of the drive where the game folder is located, instead of the original save path.

Is this in line with the design expectation?

**Comment by Bubb13** [comment]
That’s definitely not supposed to happen. I have no idea how EEex would cause something like that – it doesn’t touch any code related to saving. Maybe an antivirus on your system is blocking write permissions for InfinityLoader.exe, and is extending that block to the game itself?

**Comment by MephistoSatanDevil** [comment]
> That’s definitely not supposed to happen. I have no idea how EEex would cause something like that – it doesn’t touch any code related to saving. Maybe an antivirus on your system is blocking write permissions for InfinityLoader.exe, and is extending that block to the game itself?

Interesting. After I reinstalled it, it returned to normal.

**Comment by MephistoSatanDevil** [comment]
This issue has been reproduced, and it was also reported by others.
https://github.com/Bubb13/EEex/issues/91
