### ISSUE TITLE
Crash when attempting to use CLUAConsole commands in Debug Mode

### ISSUE THREAD

**Issue by snaphat** [Bubb13/EEex#81]
### Steps to reproduce:
1) Install BGEE with SOD v2.6.6
2) Use DLCMerger (probably unrelated?)
3) Add `SetPrivateProfileString('Program Options','Debug Mode','1')` to `Baldur.lua` (using default Baldur.lua)
4) Install EEex
5) Run `InfinityLoader.exe`
6) Start new game
7) ctrl-spacebar
8) Type `C:aaaa()` or `CluaConsole:aaaa()` and hit enter
9) Crash
 
### WeiDU.Log
```
// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~DLCMERGER/DLCMERGER.TP2~ #0 #3 // Merge DLC into game -> Merge all available DLCs: 1.7
~EEEX/EEEX.TP2~ #0 #0 // EEex: v0.10.2.1-alpha
```

### Platform
```
OS Name	Microsoft Windows 11 Pro
Version	10.0.26100 Build 26100
```

### Crash Dump
[dump.2.6.6.0.0015.zip](https://github.com/user-attachments/files/18247437/dump.2.6.6.0.0015.zip) (Compressed ~1.5MB; Uncompressed ~55.1MB)

**Comment by rd553** [comment]
Encountered what I presume is this exact same issue, but in IWDEE. Steps to reproduce are largely identical, with two distinctions.

a) Crashes only seem to occur when entering invalid console commands. I accidentally typed "AddItem" and got a crash; the correct "CreateItem" worked as expected.
b) Crashes only occurred when another mod was installed alongside EEex. The specific mod doesn't seem to matter - I tested seperately with EE Fixpack, IWD NPCs, and Artisan Kitpack, and all produced identical crashes.

**Comment by snaphat** [comment]
> Encountered what I presume is this exact same issue, but in IWDEE. Steps to reproduce are largely identical, with one difference. Crashes only seem to occur when entering invalid console commands. I accidentally typed "AddItem" and got a crash; the correct "CreateItem" worked as expected.
> 

Just to note, I did not test if only invalid commands result in a crash. Given your report in IWDEE, I suspect valid commands would work as expected as well

**Comment by Bubb13** [comment]
Thanks for reporting - this will be fixed in the next version.
